# Lab1

## Numpy

In [1]:
import numpy as np

### Basic exercises 

####  Create a 1D array of numbers from 0 to 9

In [2]:
# Solution
result = np.arange(10)
print(result)

[0 1 2 3 4 5 6 7 8 9]


#### Create a 3×3 numpy array of all True’s

In [3]:
# Solution
result = np.ones((3, 3), dtype=bool)
print(result)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#### Replace all odd numbers in arr with -1

In [4]:
# Input
arr = np.arange(10)

# Solution
print("Original:")
print(arr)

print("\nReplaced:")
arr[arr % 2 != 0] = -1
print(arr)

Original:
[0 1 2 3 4 5 6 7 8 9]

Replaced:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Replace all odd numbers in arr with -1 without changing arr

In [5]:
# Input
arr = np.arange(10)

# Solution
print("Original:")
print(arr)

print("\nReplaced copy:")
result = np.where(arr % 2 == 1, -1, arr)
print(result)

Original:
[0 1 2 3 4 5 6 7 8 9]

Replaced copy:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Convert a 1D array to a 2D array with 2 rows

In [6]:
# Input
arr = np.arange(10)

# Solution
print("Original:")
print(arr)

print("\nConverted:")
result = np.reshape(arr, (2, -1))
print(result)

Original:
[0 1 2 3 4 5 6 7 8 9]

Converted:
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Stack arrays a and b vertically and then horizontally

In [7]:
# Input
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

# Solution
print("a:")
print(a)
print("\nb:")
print(b)

print("\nVertically stacked:")
result_v = np.vstack((a, b))
print(result_v)
print("\nHorizontally stacked:")
result_h = np.hstack((a, b))
print(result_h)

a:
[[0 1 2 3 4]
 [5 6 7 8 9]]

b:
[[1 1 1 1 1]
 [1 1 1 1 1]]

Vertically stacked:
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

Horizontally stacked:
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### Get the common items between a and b

In [8]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
result = np.intersect1d(a, b)
print(result)

[2 4]


#### From array a remove all items present in array b

In [9]:
# Input
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Solution
result = a[~np.isin(a, b)]
print(result)

[1 2 3 4]


#### Find positions where elements of a and b match

In [10]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
result = np.where(a == b)[0]
print(result)

[1 3 5 7]


####  Get all items between 5 and 10 from a

In [11]:
# Input
a = np.arange(15)

# Solutions
result = a[(a >= 5) & (a <= 10)]
print(result)

[ 5  6  7  8  9 10]


#### Swap columns 1 and 2 in the array arr

In [12]:
# Input
arr = np.arange(9).reshape(3, 3)

# Solution
print("Original:")
print(arr)

print("\nSwapped:")
arr[:, [1, 2]] = arr[:, [2, 1]]
print(arr)

Original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Swapped:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


#### Reverse the rows and the columns of a 2D array arr

In [13]:
# Input
arr = np.arange(9).reshape(3, 3)

# Solution
print("Original:")
print(arr)

print("\nRows reversed:")
result_r = np.flip(arr, 0)
print(result_r)

print("\nColumns reversed:")
result_c = np.flip(arr, 1)
print(result_c)

Original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Rows reversed:
[[6 7 8]
 [3 4 5]
 [0 1 2]]

Columns reversed:
[[2 1 0]
 [5 4 3]
 [8 7 6]]


#### Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [14]:
# Solutions
result = np.random.uniform(5, 10, (5, 3))
print(result)

[[9.69088572 7.43806483 5.5371368 ]
 [5.08630122 6.23349042 7.77719864]
 [7.3886225  6.93808473 9.95828026]
 [8.30007501 7.51878976 7.59017085]
 [9.28371481 5.64941046 6.01942395]]


#### Get the positions of top 5 maximum values in a given array a

In [15]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
print("Given array:")
print(a)

print("\nTop 5 maximum values indexes:")
result = (-a).argsort()[:5]
print(result)

Given array:
[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]

Top 5 maximum values indexes:
[15 10  3  7 18]


#### Compute the counts of unique values row-wise
    Input:
    [[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
    [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
    [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
    [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
    [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
    [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]]

    Desired Output:
    [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
    [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
    [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
    [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
    [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
    [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [16]:
# Input
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

# Solution
print("Given array:")
print(arr)

print("\nCounts of unique values row-wise:")
result = np.vstack([np.bincount(row, minlength=arr.shape[1] + 1) for row in arr])[:, 1:]
print(result)

Given array:
[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]

Counts of unique values row-wise:
[[1 0 2 1 1 1 0 2 2 0]
 [2 1 3 0 1 0 1 0 1 1]
 [0 3 0 2 3 1 0 1 0 0]
 [1 0 2 1 0 1 0 2 1 2]
 [2 2 2 0 0 1 1 1 1 0]
 [1 1 1 1 1 2 0 0 2 1]]


#### Compute the min-by-max (i.e. min/max) for each row for given 2d numpy array

In [17]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

# Solution
print("Given array:")
print(a)

print("\nMin/max array:")
result = np.min(a, axis= 1) / np.max(a, axis= 1)
print(result)

Given array:
[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]

Min/max array:
[0.44444444 0.125      0.5        1.         0.11111111]


####  Find the duplicate entries in the given numpy array and mark them as True. First time occurrences should be False.

In [18]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)

# Solution
print("Given array:")
print(a)

print("\nBoolean array:")
result = np.full(a.shape[0], True)
indices = np.unique(a, return_index=True)[1]
result[indices] = False
print(result)

Given array:
[0 0 3 0 2 4 2 2 2 2]

Boolean array:
[False  True False  True False False  True  True  True  True]


#### Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
Make use of 
1. numpy.diff
2. numpy.sign
3. numpy.diff
4. numpy.where

In [19]:
# Input:
a = np.array([1, 3, 7, 8, 2, 6, 0, 1])

# Solution
print("Given array:")
print(a)

print("\nPeaks:")
diff = np.diff(np.sign(np.diff(a)))
result = a[np.where(diff == -2)[0] + 1]
print(result)

Given array:
[1 3 7 8 2 6 0 1]

Peaks:
[8 6]


#### Find the index of 5th repetition of number 1 in x
Make use of numpy.where

In [20]:
# Input
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

# Solution
print("Given array:")
print(x)

print("\nIndex of 5th repetition of number 1:")
result = np.where(x == 1)[0][n - 1]
print(result)

Given array:
[1 2 1 1 3 4 3 1 1 2 1 1 2]

Index of 5th repetition of number 1:
8


#### Compute the moving average of window size 3, for the given 1D array
Make use of numpy.convolve

In [21]:
# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
window_size = 3

# Solution
result = np.convolve(arr, np.ones(window_size), 'valid') / window_size
print(result)

[6.33333333 6.         5.66666667 4.66666667 3.66666667 2.
 3.66666667 3.        ]


### Iris dataset

#### Import the iris dataset from iris.txt
See np.genfromtxt, load the dataset with dtype=np.str

In [22]:
# Input filepath
filepath = "../data/iris.txt"

# Solution
print("Dataset sample:")
data = np.genfromtxt(filepath, dtype=np.str, delimiter=",")
print(data[0:5])

Dataset sample:
[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']]


<ipython-input-22-d991505b195a>:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data = np.genfromtxt(filepath, dtype=np.str, delimiter=",")


#### Print the unique labels of the dataset

In [23]:
# Solution
print("Unique labels:")
result = np.unique(data[:, 4])
print(result)

Unique labels:
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


#### Find how many samples (i.e. rows) we have for each unique label

In [24]:
# Solution
print("Unique samples:")
labels, counts = np.unique(data[:, 4], return_counts=True)
result = {label: count for label, count in zip(labels, counts)}
print(result)

Unique samples:
{'Iris-setosa': 50, 'Iris-versicolor': 50, 'Iris-virginica': 50}


#### Find the mean, median, standard deviation of iris's sepallength (1st column)
See np.genfromtxt, load only the 1st column with the appropiate data type

In [25]:
# Solution
sepallength = np.genfromtxt(filepath, usecols=0, dtype=np.double, delimiter=",")
mean = np.mean(sepallength)
median = np.median(sepallength)
std = np.std(sepallength)
print("Result:\nMean: " + str(mean) + "\nMedian: " + str(median) + "\nStd: " + str(std))

Result:
Mean: 5.843333333333334
Median: 5.8
Std: 0.8253012917851409


####  Find the mean, median, standard deviation of iris's sepallength (1st column) for each unique labels

In [26]:
# Solution
labels = data[:, 4]
unique = np.unique(labels)
labels_lengths = { label: sepallength[labels == label] for label in unique }

for label, lengths in labels_lengths.items():
    print(label + ":")
    print("Mean: " + str(np.mean(lengths)))
    print("Median: " + str(np.median(lengths)))
    print("Std: " + str(np.std(lengths)) + "\n")

Iris-setosa:
Mean: 5.006
Median: 5.0
Std: 0.3489469873777391

Iris-versicolor:
Mean: 5.936
Median: 5.9
Std: 0.5109833656783751

Iris-virginica:
Mean: 6.587999999999998
Median: 6.5
Std: 0.6294886813914926



#### Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
See pearsonr function from scipy

In [27]:
# Solution
from scipy.stats.stats import pearsonr

sepal = data[:, 0].astype(np.double)
petal = data[:, 2].astype(np.double)
result = pearsonr(sepal, petal)[0]
print("Pearson correlaton:")
print(result)

Pearson correlaton:
0.8717541573048713


####  Find out if iris has any missing values
See np.genfromtxt, load only columns from 0 to 4 with appropriate data type

In [28]:
# Solution
print("Does Iris contain missing values?")
filled = np.genfromtxt(filepath, delimiter=',', dtype=str, filling_values="", usecols=[0, 1, 2, 3, 4])
result = np.any(filled == "")
print(result)

Does Iris contain missing values?
False


#### Bin the petal length (3rd) column of iris to form a text array, such that if petal length is:
    Less than 3 --> 'small'
    3-5 --> 'medium'
    >=5 --> 'large'
See numpy.digitize

In [29]:
# Solution
print("Binned array:")
lengths = data[:, 2].astype(np.double)
indices = np.digitize(lengths, [0, 3, 5])
labels = {1: 'small', 2: 'medium', 3: 'large'}
result = [labels[index] for index in indices]
print(result)

Binned array:
['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', '

####  Create a new column for volume in iris, where volume is (pi x petallength x sepal_length^2)/3

In [30]:
# Solution
print("Original:")
print(data[0:5])

print("\nAfter adding \"Volume\" column:")
sepal = data[:, 0].astype(np.double)
petal = data[:, 2].astype(np.double)
volume = np.pi * petal * (sepal ** 2) / 3
column = volume.reshape(volume.shape[0], 1)
result = np.hstack((data, column))
print(result[0:5])

Original:
[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']]

After adding "Volume" column:
[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa' '38.13265162927291']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa' '35.200498485922445']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa' '30.0723720777127']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa' '33.238050274980004']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa' '36.65191429188092']]


#### Randomly sample iris's species such that setosa is twice the number of versicolor and virginica
See numpy.random.choice

In [31]:
print("Sample:")
species = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
result = np.random.choice(species, 10, p=[0.5, 0.25, 0.25])
print(result)

Sample:
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa']


#### Sort the iris dataset based on sepallength column

In [32]:
# Solution
print("Original:")
print(data[0:5])

print("\nSorted:")
indices = np.argsort(data[:, 0].astype(np.double))
result = data[indices, :]
print(result[0:5])

Original:
[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']]

Sorted:
[['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['4.4' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '3.0' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.5' '2.3' '1.3' '0.3' 'Iris-setosa']]


#### Find the most frequent value of petal length (3rd column) in iris dataset

In [33]:
# Solution
print("Most frequent value of petal length:")
lengths = data[:, 2].astype(np.double)
unique, counts = np.unique(lengths, return_counts=True)
result = unique[np.argmax(counts)]
print(result)

Most frequent value of petal length:
1.5


#### Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

In [34]:
# Solution
print("Position of the first occurrence of a value greater than 1.0:")
widths = data[:, 3].astype(np.double)
result = np.argmax(widths > 1.0)
print(result)

Position of the first occurrence of a value greater than 1.0:
50


####  Find the 5th and 95th percentile of iris's sepallength

In [35]:
# Solution
lengths = data[:, 0].astype(np.double)
result = np.percentile(lengths, [5, 95])
print("5th percentile: " + str(result[0]))
print("95th percentile: " + str(result[1]))

5th percentile: 4.6
95th percentile: 7.254999999999998


#### Get the rows having petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [36]:
# Solution
print("Rows having petallength > 1.5 and sepallength < 5.0:")
petal = data[:, 2].astype(np.double)
sepal = data[:, 0].astype(np.double)
result = data[(petal > 1.5) & (sepal < 5.0)]
print(result)

Rows having petallength > 1.5 and sepallength < 5.0:
[['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['4.9' '2.4' '3.3' '1.0' 'Iris-versicolor']
 ['4.9' '2.5' '4.5' '1.7' 'Iris-virginica']]
